server:
  host: 127.0.0.1
  port: 8080

database:
  username: root
  password: Welcome@123
  dbhost: localhost
  dbport: 3306
  dbname: pismodb

  #url: root:Welcome@123@tcp(localhost:3306)/pismodb?parseTime=true

  